---
title: "文献及模型理论"
author: "xuexuan"
date: "2020/5/5"
output: html_document
---

## **二、文献及模型理论**
### （一）文献综述
&emsp;&emsp;数学模型能很好地揭示传染病传播的主要因素和规律。鉴于新冠肺炎的传播机理，许多学者利用SIR、SEIR和SEIAR等仓室模型来研究新冠肺炎在中国的传播、预测及控制措施评价。为疫情的控制提供了理论和科学评价依据。  
&emsp;&emsp;SEIR模型是病毒传播研究中的常用模型，它能够清晰地描述出病毒传播逻辑关系，给出较为准确的趋势预测，因而被广泛采用。徐娟年、马冉、赵中睿依据山东省2020年1月23日至3月15日的疫情数据建立SEIR模型，预测疫情的高峰期。同时，基于现有数据对未来基本再生数的变化趋势加以预测。王思远、谭瀚霖、李东杰建立一个改进的传染动力学SEIR模型用于预测湖北省COVID-2019疫情发展趋势，与现有其他 SEIR 模型不同的是，本研究通过易感人群减少率$\lambda$建模政府管控措施，较好地模拟了政府干预措施逐渐增强的现象。杨俊元、张烁、王国强、李学志利用国家公布有关新冠肺炎疫情数据直接计算SIR、SEIR和SEIAR模型的基本再生数，能克服参数估计带来的误差。曹盛力、冯沛华、时朋朋建立了联合考虑潜伏期传播能力和追踪隔离干预措施的COVID-19 SEIR传播动力学模型。  
&emsp;&emsp;本文在现有研究的基础上，通过构建修正SEIR模型，一方面考虑了潜伏期患者的传播风险,另一方面也考虑了防控隔离等手段对于疫情演化的影响。  

### （二）模型理论一  
&emsp;&emsp;经典SEIR模型将人群分为易感者（susceptible,S）、感染者（infected,I）、潜伏者（exp osed,E)和康复人群（recovered,R）。该模型还假设人群中所有个体都有被感染的概率,当被感染个体痊愈后,会产生抗体,即康复人群R不会再被感染。考虑到防治传染病的隔离措施, 模型中的人群组别新增隔离易感者（$S_{q}$）、隔离潜伏者（$E_{q}$）和隔离感染者（$I_{q}$）。鉴于隔离感染者会立即送往定点医院隔离治疗,因此这部分人群在本模型中全部转化为住院患者$H$。因此,本文修订的模型中$S、I、E$分别指隔离措施遗漏的易感者、感染者和潜伏者。隔离易感者解除隔离后重新转变为易感者,而感染者和潜伏者均有不同程度的能力感染易感者,使其转化为潜伏者。  
&emsp;&emsp;假设隔离比例为$q$，传染概率为$\beta$，接触率为$c$，$\rho$是有效接触系数，有效接触系数的参考值取1，$\rho c$是有效接触率。易感者$S$向隔离易感者$S_{q}$、隔离潜伏者$E_{q}$、潜伏者$E$的转化速率为$\rho cq(1-\beta)$、$\rho c\beta q$ 和$\rho c\beta(1-q)$。同时考虑到非隔离的感染者$I$和潜伏者$E$对易感人群的影响，又有隔离解除的易感者$S_{q}$重新转变为$S$，因此易感者人数控制方程为  
<div align=center>  
$$ds/dt=-[\rho c\beta+\rho cq(1-\beta)]S(I+\theta E)+\lambda S_{q}\tag{1} $$
</div>  
&emsp;&emsp;其中$\theta$是潜伏者相对于感染者传播能力的比值，简单起见假设潜伏期患者与已表现出症状患者的传染能力相同，即$\theta=1$。$\lambda$是隔离解除速率，取$\lambda=1/14$（隔离时长为14d）。  
&emsp;&emsp;用于COVID-19疫情的修正SEIR动力学方程构建如下:  

$$
\left\{ 
\begin{array}{c}
    ds/dt=-[\rho c\beta+\rho cq(1-\beta)]S(I+\theta E)+\lambda S_{q} \\ 
    dE/dt=\rho c\beta(1-q)]S(I+\theta E)-\sigma E\\ 
    dI/dt=\sigma E-(\delta_{I}+\alpha+\gamma_{I})I\\
    dS_{q}/dt=\rho cq(1-\beta)]S(I+\theta E)-\lambda S_{q}\\
    dE_{q}/dt=\rho c\beta qS(I+\theta E)-\delta_{q}E_{q}\\
    dH/dt=\delta_{I}I+\delta_{q}E_{q}-(\alpha+\gamma_{H})H\\
    dR/dt=\gamma_{I}I+\gamma_{H}H
\end{array}
\right. 
\tag{2}
$$  


&emsp;&emsp;其中,$\sigma$为潜伏者向感染者的转化速率，取$\sigma=1/7$（潜伏期为7d），$\alpha$为病死率，$\delta_{I}$感染者的隔离速率，$\gamma_{I}$是感染者的恢复率.$\delta_{q}$是隔离潜伏者向隔离感染者的转化速率，$\gamma_{H}$是隔离感染者的恢复速率。  

###  （三）模型理论二  
&emsp;&emsp;在SEIR模型中，易感人群在一开始会经历潜伏期，潜伏期过后才会出现症状，并且病毒在潜伏期也具有传染性。本文针对该模型设置了4个假定：  
&emsp;&emsp;（1）只存在人传人；  
&emsp;&emsp;（2）现阶段没有治疗的特效药和疫苗；  
&emsp;&emsp;（3）不考虑外界环境因素对病死率等参数的影响；  
&emsp;&emsp;（4）忽略人口出生、死亡与国际间流动人口。  
&emsp;&emsp;模型中,全部人群（N）可分为五类：未被感染的个体易感人群（S）、与感染者密切接触过的个体潜伏人群（E）、处于感染状态且还能感染易感人群的个体-感染人群（I）、治愈出院的个体-移除人群（R）、死亡患者（D）。$S_{i}$、$E_{i}$、$I_{i}$、$R_{i}$和$D_{i}$分别表示第$i$天的易感人数、潜伏人数、感染人数、和移除人数和死亡人数。$\gamma$表示感染者康复的概率,$\beta_{1}$表示易感者的感染概率,$\beta_{2}$表示潜伏者传染给易感者的概率，$\alpha$表示潜伏者转化为感染者的概率,r1表示感染者每天接触的人数,r2表示潜伏者每天接触的人数，$k$为患者的死亡率。则有如下微分方程组:
$$
\left\{ 
\begin{array}{c}
    S_{i}=S_{i-1}-r_{1}\beta_{1}I_{i-1}S_{i-1}/N-r_{2}\beta_{2}E_{i-1}S_{i-1}/N \\ 
    E_{i}=E_{i-1}+r_{1}\beta_{1}I_{i-1}S_{i-1}/N-\alpha E_{i-1}+ r_{2}\beta_{2}E_{i-1}S_{i-1}/N\\ 
    I_{i}=I_{i-1}+\alpha E_{i-1}-(k+\gamma)I_{i-1}\\
     R_{i}=R_{i-1}+\gamma I_{i-1}\\
    D_{i}=D_{i-1}+kI_{i-1}
\end{array}
\right. 
\tag{3}
$$  
&emsp;&emsp;其中$i$表示新型冠状肺炎传播的天数，N表示总人数,$N_{i}$=$S_{i}$+$E_{i}$+$I_{i}$+$R_{i}$+$D_{i}$。

















