---
title: "Untitled"
author: "xuexuan"
date: "2020/6/11"
output: 
  ioslides_presentation:
    smaller: true
    widecreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 1. 绪论


- 1.1 研究背景

- 1.2 文献综述  


## 1.1 研究背景  
&emsp;&emsp;2019年12月中旬以来，湖北省武汉市短期内出现以发热、乏力、咳嗽、呼吸不畅等为主要症状的不明原因肺炎病例。随着疫情的扩散，我国其他地区及境外也相继出现此类病例。研究发现，该疾病的元凶是一种新型冠状病毒，该病原感染所致的肺炎称为新型冠状病毒肺炎。疫情发生后，党中央和国务院高度重视，中央成立应对疫情工作领导小组。习近平总书记作出重要指示，强调要把人民群众生命安全和身体健康放在第一位，把疫情防控工作作为当前最重要的工作来抓。全国各省市也启动了突发公共卫生事件一级响应机制，采取有力措施，坚决打赢疫情防控阻击战。截至2020年6月10日24时，我国累计报告确诊病例83057例，现有确诊病例62例，国内疫情已经相对稳定。本文在现有研究的基础上，主要利用极大似然估计方法对SEIR模型中的参数进行估计，进而利用SEIR模型对疫情进行分析。

## 1.2 文献综述  
&emsp;&emsp;[1]曹志东、王劲峰等（2009），构建了反映SARS传播过程的动力学模型,利用模拟退火算法对2003年广州市的SARS疫情进行了研究，得到了潜伏期、感染期、基本再生数与有效再生数的最优估计；  

&emsp;&emsp;[2]王小莉、曹志东等（2011），利用北京市2009年8月3日至9月27日经校正的甲型H1N1流感样病例数，建立SEIR模型,对国庆后甲型H1N1流感的流行趋势及高峰达到时间进行预测。在研究过程中，采用模拟退火算法进行流行病学参数的优化；  

&emsp;&emsp;[3]蔡磊（2016），根据2014-2015年西非埃博拉病毒数据，采用极大似然估计方法，运用三类传染病动力学模型(SIR模型、SEIR模型和SEIHFR模型)，分别对总体、几内亚、塞拉利昂和利比里亚的疫情进行实证分析；

&emsp;&emsp;[4]耿辉、徐安定等（2020）建立SEIR模型，加入潜伏期传染率、感染人群变化率等新参数，分析防控手段的有效性；  

&emsp;&emsp;[5]黄森忠、彭志行等（2020）基于自2019年12月12日以来发布的确诊数据，对新型冠状病毒肺炎 疫情的流行趋势进行了研判，对疾控策略的效率进行了评估。








