---
subtitle: "**基于SEIR模型对我国新冠疫情分析**"
author: "田思琪 李志伟 崔梦韬 薛璇 燕明琪"
date: "2020/6/5"
output:
  ioslides_presentation: 
    widescreen: true
    bigger: true
mathjax: local
pagemargins: 2.5
fontsize: 12
---


## 4. 基于模拟退火算法估计SEIR模型参数

### <font size=6>**4.1 SEIR模型**</font>

### <font size=6>**4.2 模拟退火算法**</font>

### <font size=6>**4.3 定量解析方法**</font>

### <font size=6>**4.4 参数估计结果及分析**</font>

## **4.1 SEIR模型**
本文所建立的SEIR模型不考虑小概率出现的“超级传播事件”的影响。考虑到出现疫情以后，各地纷纷出台了各项政策对疫情的发展进行干扰，所以我们在通常的SEIR模型中，对感染率$\beta$进行了重新定义，我们假设在控制措施实施以前，感染率$\beta$是一个不变的数$\beta$,在各种控制措施实施以后，感染率$\beta$将呈指数下降，即感染率为$\beta(t)=\beta*e^{(-kt)}$。
## **4.1 SEIR模型**
本文所建的SEIR模型为
$$
\frac{dS}{dt}=-\beta e^{(-kt)}\frac{S(t)I(t)}{N}
$$
$$
\frac{dE}{dt}=\beta e^{(-kt)}\frac{S(t)I(t)}{N}-\delta E(t)
$$
$$
\frac{dI}{dt}=\delta E(t)-\gamma I(t)
$$
$$
\frac{dR}{dt}=\gamma I(t)
$$

## **4.2 模拟退火算法**
模拟退火算法是一种启发式算法，在搜索最优解的过程中利用到了原来搜索过程中得到的信息，且这个信息会改进我们的搜索过程。与爬山算法相比,模拟退火算法在搜索过程引入了随机因素，它会以一定的概率来接受一个比当前解要差的解，因此有可能会跳出这个局部的最优解，达到全局的最优解。其基本思想是：
* （1）随机生成一个解$A$, 计算解 A 对应的目标函数值$f(A)$；

* （2）在$A$附近随机生成一个解$B$，计算解$B$对应的目标函数值$f(B)$；

* （3）如果$f(B)<f(A)$, 则将解$B$赋值给解$A$，然后重复上面步骤（爬山法的思想）；如果$f(B)\geq f(A)$, 那么我们计算接受$B$的概率$P_t=e^{(-\mid f(B)-f(A)\mid)\times C_t}$，然后我们生成一个[0,1]之间的随机数$r$，如果$r<p$，我们就将解$B$赋值给解$A$，然后重复上面的步骤;否则我们返回第(2)步，在原来的$A$附近再重新生成一个解$B$，然后继续下去。

## **4.3 定量解析方法**
本文拟采用模拟退火的方法对流行病学参数进行优化。令每日新增的新冠肺炎病例数的观察值为$obs_i(i=1,2,...,T)$,根据SEIR模型求解的每日新增新冠肺炎病例数为$est_i(i=1,2,...,T$,则本文设定模拟退火算法的目标函数$loss$的计算公式为：
$$
loss=1-\frac{\sum_{i=1}^{T}(obs_i-est_i)^2}{\sum_{i=1}^{T}(obs_i-\frac{\sum_{i=1}^{T}obs_i}{N})^2}
$$

## **4.3 定量解析方法**
* 首先设置初始值$ST_0=\{S_0,E_0,I_0,R_0\}$,任意指定控制参数集$P=\{\beta,k,\delta,\gamma\}$;
 
* 利用四阶龙格库塔法解析得到与$P$对应的疫情传播的模拟数据，利用目标函数计算$loss$;
 
* 对控制参数集$P$进行随机扰动，即在参数集中随机挑选一个参数，在该参数上增加一个服从正态分布的随机扰动项，其他参数不变，得到一个新的参数集$P'$,计算与$P'$对应的目标函数值$loss'$;


## **4.3 定量解析方法**
利用Metropolis准则用$P'$代替$P$：
$$
\begin{cases}
p(P\to P')=1 &loss'\leq loss\\
p(P\to P')=exp(\frac{loss-loss'}{c}) &loss'>loss
\end{cases}
$$
其中，$p(P\to P')$表示$P'$代替$P$的概率，c为温度参数，它是一个变量，在循环迭代过程中，每执行一次$loss'>loss$的概率选择，c会按一定比例逐渐变小，当迭代结束之后，最后一次扰动无效的前一个参数集$P$就是近似的最优控制参数集。





