---
title: "基于SEIR模型的新冠疫情分析"
author: "Cui"
date: "2020/5/2"
output:
  html_document:
    toc: yes

---

# 1.研究背景及意义

## 1.1 研究背景

&emsp;&emsp;在2019年12月1日，新型冠状肺炎的已知第一例病例出现，该病例并没有直接接触华南海鲜批发市场。在2019年12月10日，第一例与华南海鲜批发市场有关的病例出现。在2019年12月12日，国家卫健委确认了武汉的首个新冠肺炎病例。2020年1月7日，专家检测出病毒为新型冠状肺炎。2020年1月15日，国家疾控中心启动一级应急响应。2020年1月20日，南山院士确认该病毒存在“有人传人，存在医务人员感染”的情况，同日，国务院将新冠肺炎纳入法定传染病。2020年1月23日上午10点武汉封城。2020年1月24日，湖北省启动突发公共卫生事件Ⅰ级响应。2020年1月29日，中国内地31个省区市全部启动突发公共卫生事件Ⅰ级响应。

&emsp;&emsp;由于新型冠状肺炎的迅速爆发以及新型冠状肺炎就有传染性，我国政府采取了封城、社区隔离、以及取消聚众活动等各项措施。但由于人民在家隔离，导致企业的日常运营无法展开，这引起了尤其是中小企业的债务危机加重，收入下降。同时，由于企业无法正常运营，使得人们对医疗物资以及生活必需品的需求得不到保障，因此，企业的复工复产就迫在眉睫。

&emsp;&emsp;为了保障人们对医疗物资和生活必需品的供应，我国开始实施复工复产政策。在2020年2月10日，上海市、重庆市、浙江省、江苏省、云南省等多个省市开始复工复产。湖北省在2月14日开始复工，新疆在2月15日开始复工，温州市在2月17日开始复工，甘肃省在2月20日开始复工。我国大多数省市都是在2月10日开始复工复产。由杨子晚报<sup>1</sup>可知，从开始复工复产到3月3日，全国（不包括港澳台地区）的复工指数已经达到57.42%，我国的37个主要城市的大多数的复工指数已经高于50%，尤其是西宁、大连、长春、沈阳、拉萨、青岛等城市，它们的复工指数均在60%以上。

## 1.2 研究意义
&emsp;&emsp;在本文中建立了SEIR模型，通过该模型对全国的高峰期进行预测，并比较在复工前，复工不采取防疫措施和复工采取防疫措施三种情况下的发展趋势，从而研究复工对疫情传播所造成的影响以及复工后采取防疫措施对疫情传播的影响，从而为我国复工后的防疫工作提供重要的参考价值。


